### ISSUE TITLE
Oppdater "endretAvEnhetsNr" ved endring av oppgave

### ISSUE THREAD

**Issue by ugur93** [navikt/bidrag-arbeidsflyt#87]

**Comment by jactor-rises** [comment]
@morher : bør vi bruke enhet fra journalposthendelsen til å sette dette eller bør vi legge dette i sporingsdata objektet i hendelsen og bruke dette?

**Comment by jactor-rises** [comment]
implementert i https://github.com/navikt/bidrag-arbeidsflyt/pull/88
